#include "window.h"
#include "ui_window.h"

QString Start;
QString Stop;
QString Wyswietl;

Window::Window(QWidget *parent) :
    QMainWindow(parent),
    ui(new Ui::Window)
{
    ui->setupUi(this);
    WczytajPrzystanki();
    ui->comboStart->addItem("Dubois");
    ui->comboStop->addItem("Kwiska");
}

Window::~Window()
{
    delete ui;
}

void Window::on_findButton_clicked()
{
    Wykonaj();
}

void Window::UstawSiec(Siec &MPK) {
    siec = MPK;
}

void Window::Wykonaj() {

    std::string Poczatek;
    std::string Koniec;
    std::string display;
    int linia = 1000;
    char znak = 't';
    Poczatek = ui->comboStart->currentText().toStdString();
    Koniec = ui->comboStop->currentText().toStdString();

    auto lista = siec.ZnajdzNajkrotszaDroge(Poczatek, Koniec);
    MojaTrasa* trasa = new MojaTrasa(lista);
    ParaLiniaPrzystanek* tablica = trasa->WytyczTrase(siec);

    if(tablica!= nullptr) {
            for (int i = 0; i < trasa->getLiczbaPrzystankowDoPrzejechania(); ++i) {
                if (tablica->liniaznak == ';' && tablica->linia!=1111) {
                    ostringstream temp;
                    if(tablica[i].linia != linia) {
                        linia = tablica[i].linia;
                        display += "Linia ";
                        temp << tablica[i].linia;
                        display += temp.str();
                        display += ":\n";
                    }
                    display += "     ";
                    display += tablica[i].przystanek;
                    display += "\n";
                }
                else if (tablica->linia == 1111) {
                    if(tablica[i].liniaznak != znak) {
                        znak = tablica[i].liniaznak;
                        display += "Linia ";
                        display += tablica[i].liniaznak;
                        display += ":\n";
                    }
                    display += "     ";
                    display += tablica[i].przystanek;
                    display += "\n";
                }
                else {
                    ostringstream temp;
                    if(tablica[i].linia != linia) {
                        linia = tablica[i].linia;
                        display += "Linia ";
                        temp << tablica[i].linia;
                        display += temp.str();
                        display += tablica[i].liniaznak;
                        display += ":\n";
                    }
                    display += "      ";
                    display += tablica[i].przystanek;
                    display += "\n";
                }
            }
        }
        else {
            display += "Brak trasy";
            display += "\n";
    }

    Wyswietl = QString::fromStdString(display);
    ui->textEdit->setText(Wyswietl);

}


void Window::WczytajPrzystanki() {
    ui->comboStop->addItem("9 Maja");
    ui->comboStop->addItem("AUCHAN");
    ui->comboStop->addItem("Adamczewskich");
    ui->comboStop->addItem("Adamieckiego");
    ui->comboStop->addItem("Aleja Pracy");
    ui->comboStop->addItem("Aleja Wędrowców");
    ui->comboStop->addItem("Arabska");
    ui->comboStop->addItem("Arena");
    ui->comboStop->addItem("Arkady (Capitol)");
    ui->comboStop->addItem("Armii Krajowej");
    ui->comboStop->addItem("Armii Krajowej (Bogedaina)");
    ui->comboStop->addItem("Azaliowa");
    ui->comboStop->addItem("BARDZKA");
    ui->comboStop->addItem("BARDZKA (Cmentarz)");
    ui->comboStop->addItem("BARTOSZOWICE (pętla)");
    ui->comboStop->addItem("BIELANY WROCŁAWSKIE");
    ui->comboStop->addItem("BIERUTOWSKA (Ośrodek zdrowia)");
    ui->comboStop->addItem("BIERUTOWSKA (Wiadukt)");
    ui->comboStop->addItem("BIEŃKOWICE");
    ui->comboStop->addItem("BISKUPIN");
    ui->comboStop->addItem("BLACHARSKA");
    ui->comboStop->addItem("BLIZANOWICE");
    ui->comboStop->addItem("BROCHÓW");
    ui->comboStop->addItem("BROCHÓW (Stacja kolejowa)");
    ui->comboStop->addItem("BRZEZINA (pętla)");
    ui->comboStop->addItem("Bacciarellego");
    ui->comboStop->addItem("Bagatela");
    ui->comboStop->addItem("Bajana");
    ui->comboStop->addItem("Bałtycka");
    ui->comboStop->addItem("Bałtycka (Szkolny)");
    ui->comboStop->addItem("Berenta");
    ui->comboStop->addItem("Bezpieczna");
    ui->comboStop->addItem("Białych Goździków");
    ui->comboStop->addItem("Bielany - Boczna");
    ui->comboStop->addItem("Bielany - Kościół");
    ui->comboStop->addItem("Bielany - Kwiatowa");
    ui->comboStop->addItem("Bielany - MAKRO");
    ui->comboStop->addItem("Bielany - PKP");
    ui->comboStop->addItem("Bielany - skrzyżowanie");
    ui->comboStop->addItem("Bielawa");
    ui->comboStop->addItem("Bierdzany");
    ui->comboStop->addItem("Bierutowska");
    ui->comboStop->addItem("Bierutowska 75");
    ui->comboStop->addItem("Bierzyce");
    ui->comboStop->addItem("Bierzyce - wieś");
    ui->comboStop->addItem("Biestrzyków - skrzyżowanie");
    ui->comboStop->addItem("Biskupice Podgórne Dong Seo/Dong Yang");
    ui->comboStop->addItem("Biskupice Podgórne LG Chem");
    ui->comboStop->addItem("Biskupice Podgórne LG Display");
    ui->comboStop->addItem("Biskupice Podgórne LG Electronics");
    ui->comboStop->addItem("Biskupice Podgórne LG Innotek");
    ui->comboStop->addItem("Blizanowicka");
    ui->comboStop->addItem("Bociania");
    ui->comboStop->addItem("Bogusławice");
    ui->comboStop->addItem("Bojanowska");
    ui->comboStop->addItem("Borowa - Stacja PKP");
    ui->comboStop->addItem("Borowa - skrzyżowanie");
    ui->comboStop->addItem("Borowa - szkoła");
    ui->comboStop->addItem("Borowska");
    ui->comboStop->addItem("Braterska");
    ui->comboStop->addItem("Brochowska");
    ui->comboStop->addItem("Brodnicka");
    ui->comboStop->addItem("Brodzka");
    ui->comboStop->addItem("Broniewskiego");
    ui->comboStop->addItem("Brzezia Łąka - Główna");
    ui->comboStop->addItem("Brzezia Łąka - Lipowa");
    ui->comboStop->addItem("Brzezia Łąka - cmentarz");
    ui->comboStop->addItem("Brzezina - Chrobrego");
    ui->comboStop->addItem("Brzezina - Kościół");
    ui->comboStop->addItem("Brzezina - Osiedle");
    ui->comboStop->addItem("Brzezinka Średzka - Główna");
    ui->comboStop->addItem("Brzezińska");
    ui->comboStop->addItem("Brücknera");
    ui->comboStop->addItem("Budziwojowice");
    ui->comboStop->addItem("Buforowa");
    ui->comboStop->addItem("Bujwida");
    ui->comboStop->addItem("Bukowina");
    ui->comboStop->addItem("Bukowina - skrzyżowanie");
    ui->comboStop->addItem("Bukowskiego");
    ui->comboStop->addItem("Bulwar Dedala");
    ui->comboStop->addItem("Byków");
    ui->comboStop->addItem("Byków - Bar");
    ui->comboStop->addItem("Byków - Lange");
    ui->comboStop->addItem("Bystrzycka");
    ui->comboStop->addItem("Bzowa (Centrum Zajezdnia)");
    ui->comboStop->addItem("Bąków");
    ui->comboStop->addItem("C.H. Korona");
    ui->comboStop->addItem("CENTRUM HURTU UL. GIEŁDOWA");
    ui->comboStop->addItem("Ceglana");
    ui->comboStop->addItem("Centrostal");
    ui->comboStop->addItem("Centrum Zarządzania Kryzysowego");
    ui->comboStop->addItem("Chełmońskiego");
    ui->comboStop->addItem("Chińska");
    ui->comboStop->addItem("Chociebuska");
    ui->comboStop->addItem("Chopina");
    ui->comboStop->addItem("Chwałkowska");
    ui->comboStop->addItem("Chłodna");
    ui->comboStop->addItem("Ciechocińska");
    ui->comboStop->addItem("Czajkowskiego");
    ui->comboStop->addItem("DH Astra");
    ui->comboStop->addItem("DOMASZCZYN");
    ui->comboStop->addItem("DW. ŚWIEBODZKI");
    ui->comboStop->addItem("DWORCOWA");
    ui->comboStop->addItem("DWORZEC AUTOBUSOWY");
    ui->comboStop->addItem("DWORZEC GŁÓWNY");
    ui->comboStop->addItem("DWORZEC NADODRZE");
    ui->comboStop->addItem("Damrota");
    ui->comboStop->addItem("Daszyńskiego");
    ui->comboStop->addItem("Dmowskiego");
    ui->comboStop->addItem("Dobroszycka");
    ui->comboStop->addItem("Dobroszów");
    ui->comboStop->addItem("Dolmed");
    ui->comboStop->addItem("Dolnobrzeska");
    ui->comboStop->addItem("Dolnośląska Szkoła Wyższa");
    ui->comboStop->addItem("Domaszczyn - sklep");
    ui->comboStop->addItem("Domaszczyn - skrzyżowanie");
    ui->comboStop->addItem("Domaszczyn-Dębowa");
    ui->comboStop->addItem("Domaszczyn-Trzebnicka");
    ui->comboStop->addItem("Drukarska");
    ui->comboStop->addItem("Drzewieckiego");
    ui->comboStop->addItem("Dubois");
    ui->comboStop->addItem("Dworska");
    ui->comboStop->addItem("Dworzec Główny (Stawowa)");
    ui->comboStop->addItem("Dyrekcyjna");
    ui->comboStop->addItem("Działdowska");
    ui->comboStop->addItem("Dzielna");
    ui->comboStop->addItem("Dąbrowica");
    ui->comboStop->addItem("DŁUGA (Politechnika)");
    ui->comboStop->addItem("Długa");
    ui->comboStop->addItem("Długołęka - Kościół");
    ui->comboStop->addItem("Długołęka - Nowy Urząd");
    ui->comboStop->addItem("Długołęka - SELGROS");
    ui->comboStop->addItem("Długołęka - Volvo");
    ui->comboStop->addItem("Długołęka - Wrocławska");
    ui->comboStop->addItem("Długołęka - skrzyżowanie");
    ui->comboStop->addItem("EPI");
    ui->comboStop->addItem("Eluarda");
    ui->comboStop->addItem("FAT");
    ui->comboStop->addItem("Fiołkowa");
    ui->comboStop->addItem("GAJ");
    ui->comboStop->addItem("GAJ - pętla");
    ui->comboStop->addItem("GALERIA DOMINIKAŃSKA");
    ui->comboStop->addItem("GAŁÓW (pętla)");
    ui->comboStop->addItem("GRABISZYNEK");
    ui->comboStop->addItem("GRABISZYŃSKA (Cmentarz II)");
    ui->comboStop->addItem("GRABISZYŃSKA (Cmentarz)");
    ui->comboStop->addItem("Gajowa");
    ui->comboStop->addItem("Gajowicka");
    ui->comboStop->addItem("Gajowicka (Gimnazjum nr 23)");
    ui->comboStop->addItem("Gazowa");
    ui->comboStop->addItem("Gałczyńskiego");
    ui->comboStop->addItem("Gałowska");
    ui->comboStop->addItem("Gałów - Przedszkole");
    ui->comboStop->addItem("Gałów - ferma");
    ui->comboStop->addItem("Glinianki");
    ui->comboStop->addItem("Godebskiego (AWF Wrocław)");
    ui->comboStop->addItem("Godzieszowa");
    ui->comboStop->addItem("Godzieszowa - stajnia");
    ui->comboStop->addItem("Gorlicka");
    ui->comboStop->addItem("Gospodarska");
    ui->comboStop->addItem("Grabiszyńska");
    ui->comboStop->addItem("Grabowa");
    ui->comboStop->addItem("Graniczna");
    ui->comboStop->addItem("Graniczna (Strachowicka)");
    ui->comboStop->addItem("Grawerska");
    ui->comboStop->addItem("Groblice - Kolejowa");
    ui->comboStop->addItem("Groblice II-Kotowicka");
    ui->comboStop->addItem("Grochowa");
    ui->comboStop->addItem("Gromadzka");
    ui->comboStop->addItem("Grudziądzka");
    ui->comboStop->addItem("Grunwaldzka");
    ui->comboStop->addItem("Gwiaździsta");
    ui->comboStop->addItem("Góra Kapliczna");
    ui->comboStop->addItem("Górnickiego");
    ui->comboStop->addItem("Górnicza");
    ui->comboStop->addItem("Gądowianka");
    ui->comboStop->addItem("Gąsiorowskiego");
    ui->comboStop->addItem("Gęsia");
    ui->comboStop->addItem("Głogowska");
    ui->comboStop->addItem("Głubczycka");
    ui->comboStop->addItem("Główna");
    ui->comboStop->addItem("HALLERA");
    ui->comboStop->addItem("Hala Orbita");
    ui->comboStop->addItem("Hala Stulecia");
    ui->comboStop->addItem("Hala Targowa");
    ui->comboStop->addItem("Hartmana");
    ui->comboStop->addItem("Hermanowska");
    ui->comboStop->addItem("Hippiczna");
    ui->comboStop->addItem("Hotel Wrocław");
    ui->comboStop->addItem("Hubska");
    ui->comboStop->addItem("Husarska");
    ui->comboStop->addItem("Hutmen");
    ui->comboStop->addItem("Hynka");
    ui->comboStop->addItem("IWINY - pętla");
    ui->comboStop->addItem("Ibn Siny Avicenny");
    ui->comboStop->addItem("Inflancka");
    ui->comboStop->addItem("Inowrocławska");
    ui->comboStop->addItem("Inżynierska");
    ui->comboStop->addItem("Irysowa");
    ui->comboStop->addItem("Iwiny (Rondo)");
    ui->comboStop->addItem("Iwiny - Brochowska");
    ui->comboStop->addItem("Iwiny - Kolejowa");
    ui->comboStop->addItem("Iwiny - Polna");
    ui->comboStop->addItem("Iwiny - Słoneczna");
    ui->comboStop->addItem("JAKSONOWICE");
    ui->comboStop->addItem("JANÓWEK (WOŚ)");
    ui->comboStop->addItem("JARNOŁTÓW");
    ui->comboStop->addItem("JERZMANOWO (Cmentarz I)");
    ui->comboStop->addItem("JERZMANOWO (Cmentarz II)");
    ui->comboStop->addItem("JERZMANOWO (pętla)");
    ui->comboStop->addItem("JERZMANOWSKA (pętla)");
    ui->comboStop->addItem("Jabłeczna");
    ui->comboStop->addItem("Jagodno");
    ui->comboStop->addItem("Januszkowice");
    ui->comboStop->addItem("Januszkowice - Wierzbowa");
    ui->comboStop->addItem("Janówek");
    ui->comboStop->addItem("Jarnołtowska (Krzeptowska)");
    ui->comboStop->addItem("Jarnołtowska (Samotworska)");
    ui->comboStop->addItem("Jarocińska");
    ui->comboStop->addItem("Jarzębinowa");
    ui->comboStop->addItem("Jastrzębia");
    ui->comboStop->addItem("Jaworowa");
    ui->comboStop->addItem("Jedności Narodowej");
    ui->comboStop->addItem("Jeleniogórska");
    ui->comboStop->addItem("Jerzmanowo");
    ui->comboStop->addItem("Jerzmanowska");
    ui->comboStop->addItem("Joannitów");
    ui->comboStop->addItem("Jordanowska");
    ui->comboStop->addItem("Jutrosińska");
    ui->comboStop->addItem("Jędrzejowska");
    ui->comboStop->addItem("KAMIEŃSKIEGO (pętla)");
    ui->comboStop->addItem("KIEŁCZOWSKA (LZN)");
    ui->comboStop->addItem("KIEŁCZÓW (pętla)");
    ui->comboStop->addItem("KLECINA");
    ui->comboStop->addItem("KLECINA (Stacja kolejowa)");
    ui->comboStop->addItem("KOLBUSZOWSKA (Stadion)");
    ui->comboStop->addItem("KOSZAROWA (Szpital)");
    ui->comboStop->addItem("KOSZAROWA (Uniwersytet)");
    ui->comboStop->addItem("KOWALE");
    ui->comboStop->addItem("KOZANÓW");
    ui->comboStop->addItem("KOZANÓW (Dokerska)");
    ui->comboStop->addItem("KRAKOWSKA (Centrum handlowe)");
    ui->comboStop->addItem("KROMERA");
    ui->comboStop->addItem("KRZYKI");
    ui->comboStop->addItem("KRZYŻANOWICE");
    ui->comboStop->addItem("KSIĘŻE MAŁE");
    ui->comboStop->addItem("KSIĘŻE WIELKIE");
    ui->comboStop->addItem("KUŹNIKI");
    ui->comboStop->addItem("KUŹNIKI (Stacja kolejowa)");
    ui->comboStop->addItem("Kadłubka");
    ui->comboStop->addItem("Kajdasza");
    ui->comboStop->addItem("Kamienna");
    ui->comboStop->addItem("Kamienna (Widna)");
    ui->comboStop->addItem("Kamiennogórska (Ośrodek dla niewidomych)");
    ui->comboStop->addItem("Kamień I");
    ui->comboStop->addItem("Kamień II");
    ui->comboStop->addItem("Kamień Jantarowa");
    ui->comboStop->addItem("Kamieńskiego");
    ui->comboStop->addItem("Kamieńskiego (Szpital)");
    ui->comboStop->addItem("Karwińska");
    ui->comboStop->addItem("Karłowicza");
    ui->comboStop->addItem("Kasprowicza");
    ui->comboStop->addItem("Katedra");
    ui->comboStop->addItem("Kiełczowska");
    ui->comboStop->addItem("Kiełczowska (Cmentarz)");
    ui->comboStop->addItem("Kiełczów ""Biedronka""");
    ui->comboStop->addItem("Kiełczów (pętla)/Wrocławska");
    ui->comboStop->addItem("Kiełczów - Boczna");
    ui->comboStop->addItem("Kiełczów - Mleczna");
    ui->comboStop->addItem("Kiełczów - Rzeczna");
    ui->comboStop->addItem("Kiełczów - Sielska Dolina");
    ui->comboStop->addItem("Kiełczów - WODROL");
    ui->comboStop->addItem("Kiełczów - Wrocławska");
    ui->comboStop->addItem("Kiełczów - Zgodna");
    ui->comboStop->addItem("Kiełczów - osiedle");
    ui->comboStop->addItem("Kiełczów Sosnowa");
    ui->comboStop->addItem("Kiełczów Ładna");
    ui->comboStop->addItem("Kiełczówek");
    ui->comboStop->addItem("Kiełczówek - pętla");
    ui->comboStop->addItem("Kleczkowska");
    ui->comboStop->addItem("Klimasa");
    ui->comboStop->addItem("Kliniki");
    ui->comboStop->addItem("Kmieca");
    ui->comboStop->addItem("Kochanowskiego");
    ui->comboStop->addItem("Kolejowa");
    ui->comboStop->addItem("Kolista");
    ui->comboStop->addItem("Komandorska");
    ui->comboStop->addItem("Kominiarska");
    ui->comboStop->addItem("Kominiarska-plac sportowy");
    ui->comboStop->addItem("Komuny Paryskiej");
    ui->comboStop->addItem("Konduktorska");
    ui->comboStop->addItem("Kopańskiego");
    ui->comboStop->addItem("Kopernika");
    ui->comboStop->addItem("Kosmonautów (Nowe Żerniki)");
    ui->comboStop->addItem("Kosmonautów (Szpital)");
    ui->comboStop->addItem("Koszarowa");
    ui->comboStop->addItem("Kotowice - Cmentarna");
    ui->comboStop->addItem("Kotowice - Główna");
    ui->comboStop->addItem("Kotowice - Ogrodowa");
    ui->comboStop->addItem("Kotowice II-Spacerowa/Leśna");
    ui->comboStop->addItem("Kowale (Stacja kolejowa)");
    ui->comboStop->addItem("Kowalska");
    ui->comboStop->addItem("Kowalska 56");
    ui->comboStop->addItem("Kowalska I");
    ui->comboStop->addItem("Kowieńska");
    ui->comboStop->addItem("Kozanowska");
    ui->comboStop->addItem("Kozia");
    ui->comboStop->addItem("Kołobrzeska");
    ui->comboStop->addItem("Końcowa");
    ui->comboStop->addItem("Kościelna");
    ui->comboStop->addItem("Kościuszki");
    ui->comboStop->addItem("Kośnego");
    ui->comboStop->addItem("Kośnego1");
    ui->comboStop->addItem("Krajobrazowa");
    ui->comboStop->addItem("Krakowiany");
    ui->comboStop->addItem("Krakowska");
    ui->comboStop->addItem("Krasińskiego");
    ui->comboStop->addItem("Kromera (Czajkowskiego)");
    ui->comboStop->addItem("Krucza");
    ui->comboStop->addItem("Krucza (Mielecka)");
    ui->comboStop->addItem("Krynicka");
    ui->comboStop->addItem("Krzelowska");
    ui->comboStop->addItem("Krzemieniecka");
    ui->comboStop->addItem("Królewiecka");
    ui->comboStop->addItem("Królewska");
    ui->comboStop->addItem("Krępice");
    ui->comboStop->addItem("Krępicka");
    ui->comboStop->addItem("Krępicka - szkoła");
    ui->comboStop->addItem("Księska");
    ui->comboStop->addItem("Kurpiów");
    ui->comboStop->addItem("Kutrzeby");
    ui->comboStop->addItem("Kwiatkowskiego");
    ui->comboStop->addItem("Kwiatkowskiego (Rondo)");
    ui->comboStop->addItem("Kwidzyńska");
    ui->comboStop->addItem("Kwiska");
    ui->comboStop->addItem("Kątna");
    ui->comboStop->addItem("Kątowa");
    ui->comboStop->addItem("Kąty Wilczyckie");
    ui->comboStop->addItem("Kępa");
    ui->comboStop->addItem("Kępa - Skrzyżowanie");
    ui->comboStop->addItem("Kępińska");
    ui->comboStop->addItem("Kętrzyńska");
    ui->comboStop->addItem("KŁOKOCZYCE (pętla)");
    ui->comboStop->addItem("LEŚNICA");
    ui->comboStop->addItem("LEŚNICA - Hermes");
    ui->comboStop->addItem("LIPA PIOTROWSKA");
    ui->comboStop->addItem("LITEWSKA (pętla)");
    ui->comboStop->addItem("LITOMSKA (ZUS)");
    ui->comboStop->addItem("LUTYNIA");
    ui->comboStop->addItem("Lamowice");
    ui->comboStop->addItem("Las Mokrzański");
    ui->comboStop->addItem("Las Osobowicki");
    ui->comboStop->addItem("Las Ratyński");
    ui->comboStop->addItem("Lekarska");
    ui->comboStop->addItem("Libelta");
    ui->comboStop->addItem("Lipska");
    ui->comboStop->addItem("Lubelska");
    ui->comboStop->addItem("Lutynia Osiedle");
    ui->comboStop->addItem("METALOWCÓW (Ośrodek sportu)");
    ui->comboStop->addItem("MIŃSKA (Rondo Rotm. Pileckiego)");
    ui->comboStop->addItem("MOKRY DWÓR");
    ui->comboStop->addItem("MUCHOBÓR MAŁY (Stacja kolejowa)");
    ui->comboStop->addItem("MULICKA");
    ui->comboStop->addItem("Magellana");
    ui->comboStop->addItem("Malinowa");
    ui->comboStop->addItem("Malwowa");
    ui->comboStop->addItem("Marcepanowa");
    ui->comboStop->addItem("Marchewkowa");
    ui->comboStop->addItem("Marszowice");
    ui->comboStop->addItem("Marszowicka");
    ui->comboStop->addItem("Małomicka");
    ui->comboStop->addItem("Małopanewska");
    ui->comboStop->addItem("Małopolska (Ośrodek dla niewidomych)");
    ui->comboStop->addItem("Maślice Małe");
    ui->comboStop->addItem("Maślicka");
    ui->comboStop->addItem("Maślicka - Osiedle");
    ui->comboStop->addItem("Metalowców");
    ui->comboStop->addItem("Michałowice");
    ui->comboStop->addItem("Mickiewicza");
    ui->comboStop->addItem("Mielecka");
    ui->comboStop->addItem("Mikołowska");
    ui->comboStop->addItem("Miodowa");
    ui->comboStop->addItem("Mirków - Stadion");
    ui->comboStop->addItem("Mirków - Wolności");
    ui->comboStop->addItem("Międzyrzecka");
    ui->comboStop->addItem("Miłoszycka");
    ui->comboStop->addItem("Mochnackiego");
    ui->comboStop->addItem("Modra");
    ui->comboStop->addItem("Mokra");
    ui->comboStop->addItem("Mokrzańska");
    ui->comboStop->addItem("Moniuszki");
    ui->comboStop->addItem("Monopolowa");
    ui->comboStop->addItem("Monte Cassino");
    ui->comboStop->addItem("Morelowskiego");
    ui->comboStop->addItem("Morwowa");
    ui->comboStop->addItem("Mosty Warszawskie");
    ui->comboStop->addItem("Mroźna");
    ui->comboStop->addItem("Muchobór Wielki");
    ui->comboStop->addItem("Muchobór Wielki (Roślinna)");
    ui->comboStop->addItem("Mydlice I");
    ui->comboStop->addItem("Mydlice II");
    ui->comboStop->addItem("Młodych Techników");
    ui->comboStop->addItem("NOWY DWÓR (pętla)");
    ui->comboStop->addItem("Na Grobli");
    ui->comboStop->addItem("Na Niskich Łąkach");
    ui->comboStop->addItem("Na Ostatnim Groszu");
    ui->comboStop->addItem("Na Szańcach");
    ui->comboStop->addItem("Narodowe Forum Muzyki");
    ui->comboStop->addItem("Niedziałkowskiego");
    ui->comboStop->addItem("Niedźwiedzia");
    ui->comboStop->addItem("Nowodworska");
    ui->comboStop->addItem("Nowowiejska");
    ui->comboStop->addItem("Nowy Dom");
    ui->comboStop->addItem("Nowy Dwór");
    ui->comboStop->addItem("Nowy Dwór (Rogowska)");
    ui->comboStop->addItem("Nowy Dwór (Stacja kolejowa)");
    ui->comboStop->addItem("Nyska");
    ui->comboStop->addItem("OPATOWICE");
    ui->comboStop->addItem("OPORÓW");
    ui->comboStop->addItem("OSIEDLE SOBIESKIEGO (pętla)");
    ui->comboStop->addItem("OSOBOWICE");
    ui->comboStop->addItem("OSOBOWICE (Stacja kolejowa)");
    ui->comboStop->addItem("OSOBOWICKA (Cmentarz II)");
    ui->comboStop->addItem("OSOBOWICKA (Cmentarz)");
    ui->comboStop->addItem("Obornicka (Obwodnica)");
    ui->comboStop->addItem("Oboźna");
    ui->comboStop->addItem("Odolanowska");
    ui->comboStop->addItem("Odrodzenia Polski");
    ui->comboStop->addItem("Ogród Botaniczny");
    ui->comboStop->addItem("Ojca Beyzyma");
    ui->comboStop->addItem("Okrzei");
    ui->comboStop->addItem("Oleśniczka");
    ui->comboStop->addItem("Oleśniczka - skrzyżowanie");
    ui->comboStop->addItem("Olsztyńska");
    ui->comboStop->addItem("Opatowicka nr 127");
    ui->comboStop->addItem("Opatowicka nr 59");
    ui->comboStop->addItem("Opatowicka nr 85");
    ui->comboStop->addItem("Opera");
    ui->comboStop->addItem("Opolska");
    ui->comboStop->addItem("Orla");
    ui->comboStop->addItem("Orlińskiego");
    ui->comboStop->addItem("Orzechowa");
    ui->comboStop->addItem("Os. Przyjaźni");
    ui->comboStop->addItem("Ostowa");
    ui->comboStop->addItem("Ostrowskiego");
    ui->comboStop->addItem("Owczarska");
    ui->comboStop->addItem("Ozorzyce-Krasińskiego");
    ui->comboStop->addItem("Oławska");
    ui->comboStop->addItem("Ołtaszyn");
    ui->comboStop->addItem("Ożynowa");
    ui->comboStop->addItem("PARK POŁUDNIOWY");
    ui->comboStop->addItem("PAWŁOWICE (Widawska)");
    ui->comboStop->addItem("PETRUSEWICZA");
    ui->comboStop->addItem("PIECOWICE");
    ui->comboStop->addItem("PILCZYCE");
    ui->comboStop->addItem("PILCZYCKA (Anima)");
    ui->comboStop->addItem("PL. DANIŁOWSKIEGO");
    ui->comboStop->addItem("PL. GRUNWALDZKI");
    ui->comboStop->addItem("PL. JANA PAWŁA II");
    ui->comboStop->addItem("PL. STASZICA");
    ui->comboStop->addItem("POCZTA POLSKA");
    ui->comboStop->addItem("POLANOWICE");
    ui->comboStop->addItem("POPOWICE (Stacja kolejowa)");
    ui->comboStop->addItem("PORT LOTNICZY");
    ui->comboStop->addItem("POŚWIĘCKA (Ośrodek zdrowia)");
    ui->comboStop->addItem("POŚWIĘTNE");
    ui->comboStop->addItem("PRACZE ODRZAŃSKIE");
    ui->comboStop->addItem("PRACZE ODRZAŃSKIE (Stacja kolejowa)");
    ui->comboStop->addItem("PSARY");
    ui->comboStop->addItem("PSIE POLE (Stacja kolejowa)");
    ui->comboStop->addItem("Palacha");
    ui->comboStop->addItem("Paprotna");
    ui->comboStop->addItem("Parafialna");
    ui->comboStop->addItem("Park Brochowski");
    ui->comboStop->addItem("Park Stabłowicki");
    ui->comboStop->addItem("Park Staromiejski");
    ui->comboStop->addItem("Park Szczytnicki");
    ui->comboStop->addItem("Park Tysiąclecia");
    ui->comboStop->addItem("Park Wschodni");
    ui->comboStop->addItem("Park Zachodni");
    ui->comboStop->addItem("Partynice");
    ui->comboStop->addItem("Partyzantów");
    ui->comboStop->addItem("Pasikurowice - n/ż");
    ui->comboStop->addItem("Pasikurowice-Energetyczna");
    ui->comboStop->addItem("Pasikurowice-Malinowa");
    ui->comboStop->addItem("Pasikurowice-cmentarz");
    ui->comboStop->addItem("Paulińska");
    ui->comboStop->addItem("Pawłowice");
    ui->comboStop->addItem("Pawłowicka");
    ui->comboStop->addItem("Pereca");
    ui->comboStop->addItem("Piastowska");
    ui->comboStop->addItem("Pietrzykowice");
    ui->comboStop->addItem("Piramowicza");
    ui->comboStop->addItem("Pisarzowice - Graniczna");
    ui->comboStop->addItem("Pisarzowice - Kolejowa");
    ui->comboStop->addItem("Pisarzowice - Odrzańska");
    ui->comboStop->addItem("Pisarzowice - Szkolna");
    ui->comboStop->addItem("Piwnika - Ponurego");
    ui->comboStop->addItem("Piłsudskiego");
    ui->comboStop->addItem("Pl. Hirszfelda");
    ui->comboStop->addItem("Pl. SOLIDARNOŚCI");
    ui->comboStop->addItem("Poczta Główna");
    ui->comboStop->addItem("Pola");
    ui->comboStop->addItem("Polanowicka");
    ui->comboStop->addItem("Poleska");
    ui->comboStop->addItem("Polkowicka");
    ui->comboStop->addItem("Pomorska");
    ui->comboStop->addItem("Popowice");
    ui->comboStop->addItem("Poprzeczna");
    ui->comboStop->addItem("Poznańska");
    ui->comboStop->addItem("Połabian");
    ui->comboStop->addItem("Poświęcka");
    ui->comboStop->addItem("Pracze Widawskie");
    ui->comboStop->addItem("Prudnicka");
    ui->comboStop->addItem("Prusa");
    ui->comboStop->addItem("Pruszowice - las");
    ui->comboStop->addItem("Pruszowice - wieś");
    ui->comboStop->addItem("Przebiśniegowa");
    ui->comboStop->addItem("Przedwiośnie (Stacja kolejowa)");
    ui->comboStop->addItem("Przybyszewskiego");
    ui->comboStop->addItem("Przybyły");
    ui->comboStop->addItem("Przyjaźni");
    ui->comboStop->addItem("Przystankowa");
    ui->comboStop->addItem("Psary - Parkowa");
    ui->comboStop->addItem("Psary - Szkoła");
    ui->comboStop->addItem("Psie Pole");
    ui->comboStop->addItem("Psie Pole (Gorlicka)");
    ui->comboStop->addItem("Psie Pole (Rondo Lotników Polskich)");
    ui->comboStop->addItem("Pustecka");
    ui->comboStop->addItem("Pułaskiego");
    ui->comboStop->addItem("Pułtuska");
    ui->comboStop->addItem("Północna");
    ui->comboStop->addItem("Płońskiego");
    ui->comboStop->addItem("RACŁAWICKA (pętla)");
    ui->comboStop->addItem("RATYŃ");
    ui->comboStop->addItem("ROD Bajki");
    ui->comboStop->addItem("ROD Bielany");
    ui->comboStop->addItem("ROD Mieczyk");
    ui->comboStop->addItem("ROD Oświata");
    ui->comboStop->addItem("ROD Pod Dębem");
    ui->comboStop->addItem("ROD Storczyk");
    ui->comboStop->addItem("ROD Tysiąclecia");
    ui->comboStop->addItem("ROD Zgoda");
    ui->comboStop->addItem("ROD Źródło Zdrowia");
    ui->comboStop->addItem("RUBCZAKA (Stacja kolejowa)");
    ui->comboStop->addItem("Racławicka");
    ui->comboStop->addItem("Racławicka (Gimnazjum nr 23)");
    ui->comboStop->addItem("Radio i Telewizja");
    ui->comboStop->addItem("Radomierzyce");
    ui->comboStop->addItem("Radwanice - Dębowa");
    ui->comboStop->addItem("Radwanice - Mickiewicza");
    ui->comboStop->addItem("Radwanice - Poprzeczna");
    ui->comboStop->addItem("Radwanice - Skrajna");
    ui->comboStop->addItem("Radwanice - Szkoła");
    ui->comboStop->addItem("Rakowiecka");
    ui->comboStop->addItem("Raków");
    ui->comboStop->addItem("Raków - skrzyżowanie");
    ui->comboStop->addItem("Raków - zakład");
    ui->comboStop->addItem("Ramiszów-kolonia");
    ui->comboStop->addItem("Ratyń - skrzyżowanie");
    ui->comboStop->addItem("Rdestowa");
    ui->comboStop->addItem("Redycka");
    ui->comboStop->addItem("Reja");
    ui->comboStop->addItem("Renoma");
    ui->comboStop->addItem("Robotnicza (Centrozłom)");
    ui->comboStop->addItem("Rogowska");
    ui->comboStop->addItem("Rondo");
    ui->comboStop->addItem("Rondo Obrońców Grodna");
    ui->comboStop->addItem("Roweckiego");
    ui->comboStop->addItem("Rubczaka");
    ui->comboStop->addItem("Rymarska");
    ui->comboStop->addItem("Rynek");
    ui->comboStop->addItem("Rysia");
    ui->comboStop->addItem("Rzemieślnicza");
    ui->comboStop->addItem("Różanka");
    ui->comboStop->addItem("RĘDZIN");
    ui->comboStop->addItem("RĘDZIŃSKA");
    ui->comboStop->addItem("Rękodzielnicza");
    ui->comboStop->addItem("SAMOTWÓR-PAŁAC");
    ui->comboStop->addItem("SIECHNICE - OSIEDLE");
    ui->comboStop->addItem("SIECHNICE - TIM");
    ui->comboStop->addItem("SOŁTYSOWICE");
    ui->comboStop->addItem("SPISKA (Ośrodek sportu)");
    ui->comboStop->addItem("STABŁOWICKA (Ośrodek zdrowia)");
    ui->comboStop->addItem("STADION WROCŁAW (Królewiecka)");
    ui->comboStop->addItem("STARODWORSKA (ZUW)");
    ui->comboStop->addItem("STĘPIN - pętla");
    ui->comboStop->addItem("SZCZODRE");
    ui->comboStop->addItem("SZYMANÓW");
    ui->comboStop->addItem("Samotworska");
    ui->comboStop->addItem("Samotwór - Dębowa");
    ui->comboStop->addItem("Sanocka");
    ui->comboStop->addItem("Semaforowa");
    ui->comboStop->addItem("Serbska (C.K. Agora)");
    ui->comboStop->addItem("Siechnice");
    ui->comboStop->addItem("Siechnice - CPN n ż");
    ui->comboStop->addItem("Siechnice - Elektrociepłownia");
    ui->comboStop->addItem("Siechnice - Ogrodnictwo");
    ui->comboStop->addItem("Siechnice - Staszica");
    ui->comboStop->addItem("Siechnice - Szkolna");
    ui->comboStop->addItem("Siechnice - Wiadukt");
    ui->comboStop->addItem("Siechnice - ZOZ");
    ui->comboStop->addItem("Siechnice - Zacisze");
    ui->comboStop->addItem("Siedlec-skrzyżowanie");
    ui->comboStop->addItem("Siedlec-szkoła");
    ui->comboStop->addItem("Skarbowców");
    ui->comboStop->addItem("Skarżyńskiego");
    ui->comboStop->addItem("Skała");
    ui->comboStop->addItem("Skierniewicka");
    ui->comboStop->addItem("Skwerowa");
    ui->comboStop->addItem("Smardzów - Reja");
    ui->comboStop->addItem("Smocza");
    ui->comboStop->addItem("Solskiego");
    ui->comboStop->addItem("Sosnowiecka");
    ui->comboStop->addItem("Sowia");
    ui->comboStop->addItem("Sołtysowicka");
    ui->comboStop->addItem("Spółdzielcza");
    ui->comboStop->addItem("Stabłowice");
    ui->comboStop->addItem("Stabłowicka (Szkoła Podstawowa nr 22)");
    ui->comboStop->addItem("Stadion Olimpijski");
    ui->comboStop->addItem("Stadion Wrocław (Lotnicza)");
    ui->comboStop->addItem("Stalowa");
    ui->comboStop->addItem("Stanisławowska");
    ui->comboStop->addItem("Stanki");
    ui->comboStop->addItem("Starodworska");
    ui->comboStop->addItem("Starodębowa");
    ui->comboStop->addItem("Strachowice General Aviation");
    ui->comboStop->addItem("Strachowicka");
    ui->comboStop->addItem("Strachowskiego");
    ui->comboStop->addItem("Strumykowa");
    ui->comboStop->addItem("Strzegomska 56");
    ui->comboStop->addItem("Stępin");
    ui->comboStop->addItem("Sucha");
    ui->comboStop->addItem("Sudecka");
    ui->comboStop->addItem("Sulimów");
    ui->comboStop->addItem("Suwalska");
    ui->comboStop->addItem("Swojczyce");
    ui->comboStop->addItem("Swojczycka");
    ui->comboStop->addItem("Szczecińska");
    ui->comboStop->addItem("Szczepin");
    ui->comboStop->addItem("Szczodre - Szkoła");
    ui->comboStop->addItem("Szczodre - Trzebnicka");
    ui->comboStop->addItem("Szczodre - stawy");
    ui->comboStop->addItem("Szewczenki");
    ui->comboStop->addItem("Szkocka");
    ui->comboStop->addItem("Szkolna");
    ui->comboStop->addItem("Szkoła Żerniki");
    ui->comboStop->addItem("Sztabowa");
    ui->comboStop->addItem("Szybowcowa");
    ui->comboStop->addItem("Szymanów - skrzyż.");
    ui->comboStop->addItem("Sąsiedzka");
    ui->comboStop->addItem("SĘPOLNO");
    ui->comboStop->addItem("Słoneczna");
    ui->comboStop->addItem("Słowiańska");
    ui->comboStop->addItem("TARNOGAJ");
    ui->comboStop->addItem("TRESTNO (pętla)");
    ui->comboStop->addItem("TRZMIELOWICKA (Stacja kolejowa)");
    ui->comboStop->addItem("TYNIECKA (pętla)");
    ui->comboStop->addItem("Tczewska");
    ui->comboStop->addItem("Tokary");
    ui->comboStop->addItem("Tokary - osiedle");
    ui->comboStop->addItem("Topolowa");
    ui->comboStop->addItem("Tramwajowa");
    ui->comboStop->addItem("Transbud");
    ui->comboStop->addItem("Trawowa");
    ui->comboStop->addItem("Trestno");
    ui->comboStop->addItem("Trzebnicka");
    ui->comboStop->addItem("Trzmielowicka");
    ui->comboStop->addItem("Tunelowa");
    ui->comboStop->addItem("Turoszowska");
    ui->comboStop->addItem("Twardogórska");
    ui->comboStop->addItem("Tymiankowa");
    ui->comboStop->addItem("Tyniecka");
    ui->comboStop->addItem("Tyrmanda");
    ui->comboStop->addItem("Uniwersytecka");
    ui->comboStop->addItem("Uniwersytet");
    ui->comboStop->addItem("Uniwersytet Ekonomiczny");
    ui->comboStop->addItem("Uniwersytet Medyczny");
    ui->comboStop->addItem("Urząd Wojewódzki");
    ui->comboStop->addItem("Volvo");
    ui->comboStop->addItem("Volvo - brama II");
    ui->comboStop->addItem("WAŁBRZYSKA");
    ui->comboStop->addItem("WOJANOWSKA (pętla)");
    ui->comboStop->addItem("WOJNÓW (pętla)");
    ui->comboStop->addItem("Wallenroda");
    ui->comboStop->addItem("Warmińska");
    ui->comboStop->addItem("Wawrzyniaka");
    ui->comboStop->addItem("Weigla (Szpital)");
    ui->comboStop->addItem("Wejherowska");
    ui->comboStop->addItem("Wełniana");
    ui->comboStop->addItem("Wiaduktowa");
    ui->comboStop->addItem("Widawa");
    ui->comboStop->addItem("Wiejska");
    ui->comboStop->addItem("Wielka");
    ui->comboStop->addItem("Wielkopolska");
    ui->comboStop->addItem("Wilczyce");
    ui->comboStop->addItem("Wilczyce - Dębowa");
    ui->comboStop->addItem("Wilczyce - Sosnowa");
    ui->comboStop->addItem("Wilczyce - Szkoła");
    ui->comboStop->addItem("Wilczyce - Wilczycka");
    ui->comboStop->addItem("Wilczyce - stary młyn");
    ui->comboStop->addItem("Wilkszyn (pętla)");
    ui->comboStop->addItem("Wilkszyn - Miłoszyn");
    ui->comboStop->addItem("Wilkszyn - Polna");
    ui->comboStop->addItem("Wilkszyńska");
    ui->comboStop->addItem("Wita Stwosza");
    ui->comboStop->addItem("Witkowska");
    ui->comboStop->addItem("Wiślańska");
    ui->comboStop->addItem("Wiśniowa");
    ui->comboStop->addItem("Wojanowska");
    ui->comboStop->addItem("Wojnów");
    ui->comboStop->addItem("Wojszyce");
    ui->comboStop->addItem("Wojszycka");
    ui->comboStop->addItem("Wolska");
    ui->comboStop->addItem("Wołowska");
    ui->comboStop->addItem("Wrocławski Park Przemysłowy");
    ui->comboStop->addItem("Wrocławski Park Technologiczny");
    ui->comboStop->addItem("Wschowska");
    ui->comboStop->addItem("Wysoka");
    ui->comboStop->addItem("Wysoka Osiedle");
    ui->comboStop->addItem("Wysoka-Chabrowa");
    ui->comboStop->addItem("Wysoka-Radosna");
    ui->comboStop->addItem("Wyszyńskiego");
    ui->comboStop->addItem("Wyścigowa");
    ui->comboStop->addItem("Wyższa Szkoła Bankowa");
    ui->comboStop->addItem("Wzgórze Partyzantów");
    ui->comboStop->addItem("Węgrów");
    ui->comboStop->addItem("ZABRODZIE");
    ui->comboStop->addItem("ZACHODNIA (Stacja kolejowa)");
    ui->comboStop->addItem("ZAKRZÓW");
    ui->comboStop->addItem("ZAWALNA");
    ui->comboStop->addItem("ZOO");
    ui->comboStop->addItem("Zacisze");
    ui->comboStop->addItem("Zagony");
    ui->comboStop->addItem("Zagrodnicza");
    ui->comboStop->addItem("Zagłoby");
    ui->comboStop->addItem("Zagłębiowska");
    ui->comboStop->addItem("Zajazdowa");
    ui->comboStop->addItem("Zajezdnia BOREK");
    ui->comboStop->addItem("Zajezdnia GAJ");
    ui->comboStop->addItem("Zajezdnia Obornicka");
    ui->comboStop->addItem("Zajezdnia OŁBIN");
    ui->comboStop->addItem("Zajączkowska");
    ui->comboStop->addItem("Zakrzowska");
    ui->comboStop->addItem("Zalewowa");
    ui->comboStop->addItem("Zaporoska");
    ui->comboStop->addItem("Zaprężyn");
    ui->comboStop->addItem("Zaprężyn - skrzyżowanie");
    ui->comboStop->addItem("Zarembowicza");
    ui->comboStop->addItem("Zbożowa");
    ui->comboStop->addItem("Zemska");
    ui->comboStop->addItem("Zgorzelisko");
    ui->comboStop->addItem("Zielińskiego");
    ui->comboStop->addItem("Zielna");
    ui->comboStop->addItem("Ziemniaczana");
    ui->comboStop->addItem("Zimowa");
    ui->comboStop->addItem("Zwycięska");
    ui->comboStop->addItem("ZĘBICE - pętla");
    ui->comboStop->addItem("Zębice - Prusa");
    ui->comboStop->addItem("Zębice - Trzech Lip/Prusa");
    ui->comboStop->addItem("Złotnicka");
    ui->comboStop->addItem("Złotniki");
    ui->comboStop->addItem("Złotostocka");
    ui->comboStop->addItem("most Grunwaldzki");
    ui->comboStop->addItem("most Milenijny");
    ui->comboStop->addItem("most Osobowicki");
    ui->comboStop->addItem("mosty Mieszczańskie");
    ui->comboStop->addItem("pl. Bema");
    ui->comboStop->addItem("pl. Legionów");
    ui->comboStop->addItem("pl. Nowy Targ");
    ui->comboStop->addItem("pl. Orląt Lwowskich");
    ui->comboStop->addItem("pl. Srebrny");
    ui->comboStop->addItem("pl. Strzegomski (Muzeum Współczesne)");
    ui->comboStop->addItem("pl. Wróblewskiego");
    ui->comboStop->addItem("pl. Zgody");
    ui->comboStop->addItem("ŁOZINA");
    ui->comboStop->addItem("Łosice");
    ui->comboStop->addItem("Łososiowicka");
    ui->comboStop->addItem("Łozina - Milicka");
    ui->comboStop->addItem("Łozina - Nowego Osiedla I");
    ui->comboStop->addItem("Łozina - Nowego Osiedla II");
    ui->comboStop->addItem("Łozina - Ośrodek zdrowia");
    ui->comboStop->addItem("Łozina - Wrocławska");
    ui->comboStop->addItem("Łozina - cmentarz");
    ui->comboStop->addItem("Ługowa");
    ui->comboStop->addItem("Łukaszowice");
    ui->comboStop->addItem("Łużycka");
    ui->comboStop->addItem("ŚLAZOWA (pętla)");
    ui->comboStop->addItem("ŚWIDNICKA (Dom Europy)");
    ui->comboStop->addItem("ŚWINIARY (pętla)");
    ui->comboStop->addItem("Śliczna");
    ui->comboStop->addItem("Śliwice");
    ui->comboStop->addItem("Śliwowa");
    ui->comboStop->addItem("Ślusarska");
    ui->comboStop->addItem("Ślęza (ul. Dębowa)");
    ui->comboStop->addItem("Ślęza (ul. Przystankowa)");
    ui->comboStop->addItem("Ślęza (ul. Pszenna - autostrada)");
    ui->comboStop->addItem("Śniadeckich");
    ui->comboStop->addItem("Śnieżna");
    ui->comboStop->addItem("Średzka");
    ui->comboStop->addItem("Śrubowa");
    ui->comboStop->addItem("Św. Katarzyna - Główna");
    ui->comboStop->addItem("Św. Katarzyna - Główna n ż");
    ui->comboStop->addItem("Św. Katarzyna - Parkowa");
    ui->comboStop->addItem("Św. Katarzyna - stacja");
    ui->comboStop->addItem("Św. Katarzyna - szkoła");
    ui->comboStop->addItem("Św. Katarzyna - szpital");
    ui->comboStop->addItem("Św. Katarzyna - Żernicka");
    ui->comboStop->addItem("Świdnicka");
    ui->comboStop->addItem("Świeradowska");
    ui->comboStop->addItem("Świstackiego");
    ui->comboStop->addItem("Świętokrzyska");
    ui->comboStop->addItem("ŻAR");
    ui->comboStop->addItem("ŻERNIKI WROCŁAWSKIE");
    ui->comboStop->addItem("Żelazna");
    ui->comboStop->addItem("Żernicka");
    ui->comboStop->addItem("Żernicka (Stacja kolejowa)");
    ui->comboStop->addItem("Żerniki");
    ui->comboStop->addItem("Żerniki Wr. - Kolejowa");
    ui->comboStop->addItem("Żerniki Wr. - Orla");
    ui->comboStop->addItem("Żmigrodzka (Obwodnica)");
    ui->comboStop->addItem("Żmudzka");


    ui->comboStart->addItem("9 Maja");
    ui->comboStart->addItem("AUCHAN");
    ui->comboStart->addItem("Adamczewskich");
    ui->comboStart->addItem("Adamieckiego");
    ui->comboStart->addItem("Aleja Pracy");
    ui->comboStart->addItem("Aleja Wędrowców");
    ui->comboStart->addItem("Arabska");
    ui->comboStart->addItem("Arena");
    ui->comboStart->addItem("Arkady (Capitol)");
    ui->comboStart->addItem("Armii Krajowej");
    ui->comboStart->addItem("Armii Krajowej (Bogedaina)");
    ui->comboStart->addItem("Azaliowa");
    ui->comboStart->addItem("BARDZKA");
    ui->comboStart->addItem("BARDZKA (Cmentarz)");
    ui->comboStart->addItem("BARTOSZOWICE (pętla)");
    ui->comboStart->addItem("BIELANY WROCŁAWSKIE");
    ui->comboStart->addItem("BIERUTOWSKA (Ośrodek zdrowia)");
    ui->comboStart->addItem("BIERUTOWSKA (Wiadukt)");
    ui->comboStart->addItem("BIEŃKOWICE");
    ui->comboStart->addItem("BISKUPIN");
    ui->comboStart->addItem("BLACHARSKA");
    ui->comboStart->addItem("BLIZANOWICE");
    ui->comboStart->addItem("BROCHÓW");
    ui->comboStart->addItem("BROCHÓW (Stacja kolejowa)");
    ui->comboStart->addItem("BRZEZINA (pętla)");
    ui->comboStart->addItem("Bacciarellego");
    ui->comboStart->addItem("Bagatela");
    ui->comboStart->addItem("Bajana");
    ui->comboStart->addItem("Bałtycka");
    ui->comboStart->addItem("Bałtycka (Szkolny)");
    ui->comboStart->addItem("Berenta");
    ui->comboStart->addItem("Bezpieczna");
    ui->comboStart->addItem("Białych Goździków");
    ui->comboStart->addItem("Bielany - Boczna");
    ui->comboStart->addItem("Bielany - Kościół");
    ui->comboStart->addItem("Bielany - Kwiatowa");
    ui->comboStart->addItem("Bielany - MAKRO");
    ui->comboStart->addItem("Bielany - PKP");
    ui->comboStart->addItem("Bielany - skrzyżowanie");
    ui->comboStart->addItem("Bielawa");
    ui->comboStart->addItem("Bierdzany");
    ui->comboStart->addItem("Bierutowska");
    ui->comboStart->addItem("Bierutowska 75");
    ui->comboStart->addItem("Bierzyce");
    ui->comboStart->addItem("Bierzyce - wieś");
    ui->comboStart->addItem("Biestrzyków - skrzyżowanie");
    ui->comboStart->addItem("Biskupice Podgórne Dong Seo/Dong Yang");
    ui->comboStart->addItem("Biskupice Podgórne LG Chem");
    ui->comboStart->addItem("Biskupice Podgórne LG Display");
    ui->comboStart->addItem("Biskupice Podgórne LG Electronics");
    ui->comboStart->addItem("Biskupice Podgórne LG Innotek");
    ui->comboStart->addItem("Blizanowicka");
    ui->comboStart->addItem("Bociania");
    ui->comboStart->addItem("Bogusławice");
    ui->comboStart->addItem("Bojanowska");
    ui->comboStart->addItem("Borowa - Stacja PKP");
    ui->comboStart->addItem("Borowa - skrzyżowanie");
    ui->comboStart->addItem("Borowa - szkoła");
    ui->comboStart->addItem("Borowska");
    ui->comboStart->addItem("Braterska");
    ui->comboStart->addItem("Brochowska");
    ui->comboStart->addItem("Brodnicka");
    ui->comboStart->addItem("Brodzka");
    ui->comboStart->addItem("Broniewskiego");
    ui->comboStart->addItem("Brzezia Łąka - Główna");
    ui->comboStart->addItem("Brzezia Łąka - Lipowa");
    ui->comboStart->addItem("Brzezia Łąka - cmentarz");
    ui->comboStart->addItem("Brzezina - Chrobrego");
    ui->comboStart->addItem("Brzezina - Kościół");
    ui->comboStart->addItem("Brzezina - Osiedle");
    ui->comboStart->addItem("Brzezinka Średzka - Główna");
    ui->comboStart->addItem("Brzezińska");
    ui->comboStart->addItem("Brücknera");
    ui->comboStart->addItem("Budziwojowice");
    ui->comboStart->addItem("Buforowa");
    ui->comboStart->addItem("Bujwida");
    ui->comboStart->addItem("Bukowina");
    ui->comboStart->addItem("Bukowina - skrzyżowanie");
    ui->comboStart->addItem("Bukowskiego");
    ui->comboStart->addItem("Bulwar Dedala");
    ui->comboStart->addItem("Byków");
    ui->comboStart->addItem("Byków - Bar");
    ui->comboStart->addItem("Byków - Lange");
    ui->comboStart->addItem("Bystrzycka");
    ui->comboStart->addItem("Bzowa (Centrum Zajezdnia)");
    ui->comboStart->addItem("Bąków");
    ui->comboStart->addItem("C.H. Korona");
    ui->comboStart->addItem("CENTRUM HURTU UL. GIEŁDOWA");
    ui->comboStart->addItem("Ceglana");
    ui->comboStart->addItem("Centrostal");
    ui->comboStart->addItem("Centrum Zarządzania Kryzysowego");
    ui->comboStart->addItem("Chełmońskiego");
    ui->comboStart->addItem("Chińska");
    ui->comboStart->addItem("Chociebuska");
    ui->comboStart->addItem("Chopina");
    ui->comboStart->addItem("Chwałkowska");
    ui->comboStart->addItem("Chłodna");
    ui->comboStart->addItem("Ciechocińska");
    ui->comboStart->addItem("Czajkowskiego");
    ui->comboStart->addItem("DH Astra");
    ui->comboStart->addItem("DOMASZCZYN");
    ui->comboStart->addItem("DW. ŚWIEBODZKI");
    ui->comboStart->addItem("DWORCOWA");
    ui->comboStart->addItem("DWORZEC AUTOBUSOWY");
    ui->comboStart->addItem("DWORZEC GŁÓWNY");
    ui->comboStart->addItem("DWORZEC NADODRZE");
    ui->comboStart->addItem("Damrota");
    ui->comboStart->addItem("Daszyńskiego");
    ui->comboStart->addItem("Dmowskiego");
    ui->comboStart->addItem("Dobroszycka");
    ui->comboStart->addItem("Dobroszów");
    ui->comboStart->addItem("Dolmed");
    ui->comboStart->addItem("Dolnobrzeska");
    ui->comboStart->addItem("Dolnośląska Szkoła Wyższa");
    ui->comboStart->addItem("Domaszczyn - sklep");
    ui->comboStart->addItem("Domaszczyn - skrzyżowanie");
    ui->comboStart->addItem("Domaszczyn-Dębowa");
    ui->comboStart->addItem("Domaszczyn-Trzebnicka");
    ui->comboStart->addItem("Drukarska");
    ui->comboStart->addItem("Drzewieckiego");
    ui->comboStart->addItem("Dubois");
    ui->comboStart->addItem("Dworska");
    ui->comboStart->addItem("Dworzec Główny (Stawowa)");
    ui->comboStart->addItem("Dyrekcyjna");
    ui->comboStart->addItem("Działdowska");
    ui->comboStart->addItem("Dzielna");
    ui->comboStart->addItem("Dąbrowica");
    ui->comboStart->addItem("DŁUGA (Politechnika)");
    ui->comboStart->addItem("Długa");
    ui->comboStart->addItem("Długołęka - Kościół");
    ui->comboStart->addItem("Długołęka - Nowy Urząd");
    ui->comboStart->addItem("Długołęka - SELGROS");
    ui->comboStart->addItem("Długołęka - Volvo");
    ui->comboStart->addItem("Długołęka - Wrocławska");
    ui->comboStart->addItem("Długołęka - skrzyżowanie");
    ui->comboStart->addItem("EPI");
    ui->comboStart->addItem("Eluarda");
    ui->comboStart->addItem("FAT");
    ui->comboStart->addItem("Fiołkowa");
    ui->comboStart->addItem("GAJ");
    ui->comboStart->addItem("GAJ - pętla");
    ui->comboStart->addItem("GALERIA DOMINIKAŃSKA");
    ui->comboStart->addItem("GAŁÓW (pętla)");
    ui->comboStart->addItem("GRABISZYNEK");
    ui->comboStart->addItem("GRABISZYŃSKA (Cmentarz II)");
    ui->comboStart->addItem("GRABISZYŃSKA (Cmentarz)");
    ui->comboStart->addItem("Gajowa");
    ui->comboStart->addItem("Gajowicka");
    ui->comboStart->addItem("Gajowicka (Gimnazjum nr 23)");
    ui->comboStart->addItem("Gazowa");
    ui->comboStart->addItem("Gałczyńskiego");
    ui->comboStart->addItem("Gałowska");
    ui->comboStart->addItem("Gałów - Przedszkole");
    ui->comboStart->addItem("Gałów - ferma");
    ui->comboStart->addItem("Glinianki");
    ui->comboStart->addItem("Godebskiego (AWF Wrocław)");
    ui->comboStart->addItem("Godzieszowa");
    ui->comboStart->addItem("Godzieszowa - stajnia");
    ui->comboStart->addItem("Gorlicka");
    ui->comboStart->addItem("Gospodarska");
    ui->comboStart->addItem("Grabiszyńska");
    ui->comboStart->addItem("Grabowa");
    ui->comboStart->addItem("Graniczna");
    ui->comboStart->addItem("Graniczna (Strachowicka)");
    ui->comboStart->addItem("Grawerska");
    ui->comboStart->addItem("Groblice - Kolejowa");
    ui->comboStart->addItem("Groblice II-Kotowicka");
    ui->comboStart->addItem("Grochowa");
    ui->comboStart->addItem("Gromadzka");
    ui->comboStart->addItem("Grudziądzka");
    ui->comboStart->addItem("Grunwaldzka");
    ui->comboStart->addItem("Gwiaździsta");
    ui->comboStart->addItem("Góra Kapliczna");
    ui->comboStart->addItem("Górnickiego");
    ui->comboStart->addItem("Górnicza");
    ui->comboStart->addItem("Gądowianka");
    ui->comboStart->addItem("Gąsiorowskiego");
    ui->comboStart->addItem("Gęsia");
    ui->comboStart->addItem("Głogowska");
    ui->comboStart->addItem("Głubczycka");
    ui->comboStart->addItem("Główna");
    ui->comboStart->addItem("HALLERA");
    ui->comboStart->addItem("Hala Orbita");
    ui->comboStart->addItem("Hala Stulecia");
    ui->comboStart->addItem("Hala Targowa");
    ui->comboStart->addItem("Hartmana");
    ui->comboStart->addItem("Hermanowska");
    ui->comboStart->addItem("Hippiczna");
    ui->comboStart->addItem("Hotel Wrocław");
    ui->comboStart->addItem("Hubska");
    ui->comboStart->addItem("Husarska");
    ui->comboStart->addItem("Hutmen");
    ui->comboStart->addItem("Hynka");
    ui->comboStart->addItem("IWINY - pętla");
    ui->comboStart->addItem("Ibn Siny Avicenny");
    ui->comboStart->addItem("Inflancka");
    ui->comboStart->addItem("Inowrocławska");
    ui->comboStart->addItem("Inżynierska");
    ui->comboStart->addItem("Irysowa");
    ui->comboStart->addItem("Iwiny (Rondo)");
    ui->comboStart->addItem("Iwiny - Brochowska");
    ui->comboStart->addItem("Iwiny - Kolejowa");
    ui->comboStart->addItem("Iwiny - Polna");
    ui->comboStart->addItem("Iwiny - Słoneczna");
    ui->comboStart->addItem("JAKSONOWICE");
    ui->comboStart->addItem("JANÓWEK (WOŚ)");
    ui->comboStart->addItem("JARNOŁTÓW");
    ui->comboStart->addItem("JERZMANOWO (Cmentarz I)");
    ui->comboStart->addItem("JERZMANOWO (Cmentarz II)");
    ui->comboStart->addItem("JERZMANOWO (pętla)");
    ui->comboStart->addItem("JERZMANOWSKA (pętla)");
    ui->comboStart->addItem("Jabłeczna");
    ui->comboStart->addItem("Jagodno");
    ui->comboStart->addItem("Januszkowice");
    ui->comboStart->addItem("Januszkowice - Wierzbowa");
    ui->comboStart->addItem("Janówek");
    ui->comboStart->addItem("Jarnołtowska (Krzeptowska)");
    ui->comboStart->addItem("Jarnołtowska (Samotworska)");
    ui->comboStart->addItem("Jarocińska");
    ui->comboStart->addItem("Jarzębinowa");
    ui->comboStart->addItem("Jastrzębia");
    ui->comboStart->addItem("Jaworowa");
    ui->comboStart->addItem("Jedności Narodowej");
    ui->comboStart->addItem("Jeleniogórska");
    ui->comboStart->addItem("Jerzmanowo");
    ui->comboStart->addItem("Jerzmanowska");
    ui->comboStart->addItem("Joannitów");
    ui->comboStart->addItem("Jordanowska");
    ui->comboStart->addItem("Jutrosińska");
    ui->comboStart->addItem("Jędrzejowska");
    ui->comboStart->addItem("KAMIEŃSKIEGO (pętla)");
    ui->comboStart->addItem("KIEŁCZOWSKA (LZN)");
    ui->comboStart->addItem("KIEŁCZÓW (pętla)");
    ui->comboStart->addItem("KLECINA");
    ui->comboStart->addItem("KLECINA (Stacja kolejowa)");
    ui->comboStart->addItem("KOLBUSZOWSKA (Stadion)");
    ui->comboStart->addItem("KOSZAROWA (Szpital)");
    ui->comboStart->addItem("KOSZAROWA (Uniwersytet)");
    ui->comboStart->addItem("KOWALE");
    ui->comboStart->addItem("KOZANÓW");
    ui->comboStart->addItem("KOZANÓW (Dokerska)");
    ui->comboStart->addItem("KRAKOWSKA (Centrum handlowe)");
    ui->comboStart->addItem("KROMERA");
    ui->comboStart->addItem("KRZYKI");
    ui->comboStart->addItem("KRZYŻANOWICE");
    ui->comboStart->addItem("KSIĘŻE MAŁE");
    ui->comboStart->addItem("KSIĘŻE WIELKIE");
    ui->comboStart->addItem("KUŹNIKI");
    ui->comboStart->addItem("KUŹNIKI (Stacja kolejowa)");
    ui->comboStart->addItem("Kadłubka");
    ui->comboStart->addItem("Kajdasza");
    ui->comboStart->addItem("Kamienna");
    ui->comboStart->addItem("Kamienna (Widna)");
    ui->comboStart->addItem("Kamiennogórska (Ośrodek dla niewidomych)");
    ui->comboStart->addItem("Kamień I");
    ui->comboStart->addItem("Kamień II");
    ui->comboStart->addItem("Kamień Jantarowa");
    ui->comboStart->addItem("Kamieńskiego");
    ui->comboStart->addItem("Kamieńskiego (Szpital)");
    ui->comboStart->addItem("Karwińska");
    ui->comboStart->addItem("Karłowicza");
    ui->comboStart->addItem("Kasprowicza");
    ui->comboStart->addItem("Katedra");
    ui->comboStart->addItem("Kiełczowska");
    ui->comboStart->addItem("Kiełczowska (Cmentarz)");
    ui->comboStart->addItem("Kiełczów ""Biedronka""");
    ui->comboStart->addItem("Kiełczów (pętla)/Wrocławska");
    ui->comboStart->addItem("Kiełczów - Boczna");
    ui->comboStart->addItem("Kiełczów - Mleczna");
    ui->comboStart->addItem("Kiełczów - Rzeczna");
    ui->comboStart->addItem("Kiełczów - Sielska Dolina");
    ui->comboStart->addItem("Kiełczów - WODROL");
    ui->comboStart->addItem("Kiełczów - Wrocławska");
    ui->comboStart->addItem("Kiełczów - Zgodna");
    ui->comboStart->addItem("Kiełczów - osiedle");
    ui->comboStart->addItem("Kiełczów Sosnowa");
    ui->comboStart->addItem("Kiełczów Ładna");
    ui->comboStart->addItem("Kiełczówek");
    ui->comboStart->addItem("Kiełczówek - pętla");
    ui->comboStart->addItem("Kleczkowska");
    ui->comboStart->addItem("Klimasa");
    ui->comboStart->addItem("Kliniki");
    ui->comboStart->addItem("Kmieca");
    ui->comboStart->addItem("Kochanowskiego");
    ui->comboStart->addItem("Kolejowa");
    ui->comboStart->addItem("Kolista");
    ui->comboStart->addItem("Komandorska");
    ui->comboStart->addItem("Kominiarska");
    ui->comboStart->addItem("Kominiarska-plac sportowy");
    ui->comboStart->addItem("Komuny Paryskiej");
    ui->comboStart->addItem("Konduktorska");
    ui->comboStart->addItem("Kopańskiego");
    ui->comboStart->addItem("Kopernika");
    ui->comboStart->addItem("Kosmonautów (Nowe Żerniki)");
    ui->comboStart->addItem("Kosmonautów (Szpital)");
    ui->comboStart->addItem("Koszarowa");
    ui->comboStart->addItem("Kotowice - Cmentarna");
    ui->comboStart->addItem("Kotowice - Główna");
    ui->comboStart->addItem("Kotowice - Ogrodowa");
    ui->comboStart->addItem("Kotowice II-Spacerowa/Leśna");
    ui->comboStart->addItem("Kowale (Stacja kolejowa)");
    ui->comboStart->addItem("Kowalska");
    ui->comboStart->addItem("Kowalska 56");
    ui->comboStart->addItem("Kowalska I");
    ui->comboStart->addItem("Kowieńska");
    ui->comboStart->addItem("Kozanowska");
    ui->comboStart->addItem("Kozia");
    ui->comboStart->addItem("Kołobrzeska");
    ui->comboStart->addItem("Końcowa");
    ui->comboStart->addItem("Kościelna");
    ui->comboStart->addItem("Kościuszki");
    ui->comboStart->addItem("Kośnego");
    ui->comboStart->addItem("Kośnego1");
    ui->comboStart->addItem("Krajobrazowa");
    ui->comboStart->addItem("Krakowiany");
    ui->comboStart->addItem("Krakowska");
    ui->comboStart->addItem("Krasińskiego");
    ui->comboStart->addItem("Kromera (Czajkowskiego)");
    ui->comboStart->addItem("Krucza");
    ui->comboStart->addItem("Krucza (Mielecka)");
    ui->comboStart->addItem("Krynicka");
    ui->comboStart->addItem("Krzelowska");
    ui->comboStart->addItem("Krzemieniecka");
    ui->comboStart->addItem("Królewiecka");
    ui->comboStart->addItem("Królewska");
    ui->comboStart->addItem("Krępice");
    ui->comboStart->addItem("Krępicka");
    ui->comboStart->addItem("Krępicka - szkoła");
    ui->comboStart->addItem("Księska");
    ui->comboStart->addItem("Kurpiów");
    ui->comboStart->addItem("Kutrzeby");
    ui->comboStart->addItem("Kwiatkowskiego");
    ui->comboStart->addItem("Kwiatkowskiego (Rondo)");
    ui->comboStart->addItem("Kwidzyńska");
    ui->comboStart->addItem("Kwiska");
    ui->comboStart->addItem("Kątna");
    ui->comboStart->addItem("Kątowa");
    ui->comboStart->addItem("Kąty Wilczyckie");
    ui->comboStart->addItem("Kępa");
    ui->comboStart->addItem("Kępa - Skrzyżowanie");
    ui->comboStart->addItem("Kępińska");
    ui->comboStart->addItem("Kętrzyńska");
    ui->comboStart->addItem("KŁOKOCZYCE (pętla)");
    ui->comboStart->addItem("LEŚNICA");
    ui->comboStart->addItem("LEŚNICA - Hermes");
    ui->comboStart->addItem("LIPA PIOTROWSKA");
    ui->comboStart->addItem("LITEWSKA (pętla)");
    ui->comboStart->addItem("LITOMSKA (ZUS)");
    ui->comboStart->addItem("LUTYNIA");
    ui->comboStart->addItem("Lamowice");
    ui->comboStart->addItem("Las Mokrzański");
    ui->comboStart->addItem("Las Osobowicki");
    ui->comboStart->addItem("Las Ratyński");
    ui->comboStart->addItem("Lekarska");
    ui->comboStart->addItem("Libelta");
    ui->comboStart->addItem("Lipska");
    ui->comboStart->addItem("Lubelska");
    ui->comboStart->addItem("Lutynia Osiedle");
    ui->comboStart->addItem("METALOWCÓW (Ośrodek sportu)");
    ui->comboStart->addItem("MIŃSKA (Rondo Rotm. Pileckiego)");
    ui->comboStart->addItem("MOKRY DWÓR");
    ui->comboStart->addItem("MUCHOBÓR MAŁY (Stacja kolejowa)");
    ui->comboStart->addItem("MULICKA");
    ui->comboStart->addItem("Magellana");
    ui->comboStart->addItem("Malinowa");
    ui->comboStart->addItem("Malwowa");
    ui->comboStart->addItem("Marcepanowa");
    ui->comboStart->addItem("Marchewkowa");
    ui->comboStart->addItem("Marszowice");
    ui->comboStart->addItem("Marszowicka");
    ui->comboStart->addItem("Małomicka");
    ui->comboStart->addItem("Małopanewska");
    ui->comboStart->addItem("Małopolska (Ośrodek dla niewidomych)");
    ui->comboStart->addItem("Maślice Małe");
    ui->comboStart->addItem("Maślicka");
    ui->comboStart->addItem("Maślicka - Osiedle");
    ui->comboStart->addItem("Metalowców");
    ui->comboStart->addItem("Michałowice");
    ui->comboStart->addItem("Mickiewicza");
    ui->comboStart->addItem("Mielecka");
    ui->comboStart->addItem("Mikołowska");
    ui->comboStart->addItem("Miodowa");
    ui->comboStart->addItem("Mirków - Stadion");
    ui->comboStart->addItem("Mirków - Wolności");
    ui->comboStart->addItem("Międzyrzecka");
    ui->comboStart->addItem("Miłoszycka");
    ui->comboStart->addItem("Mochnackiego");
    ui->comboStart->addItem("Modra");
    ui->comboStart->addItem("Mokra");
    ui->comboStart->addItem("Mokrzańska");
    ui->comboStart->addItem("Moniuszki");
    ui->comboStart->addItem("Monopolowa");
    ui->comboStart->addItem("Monte Cassino");
    ui->comboStart->addItem("Morelowskiego");
    ui->comboStart->addItem("Morwowa");
    ui->comboStart->addItem("Mosty Warszawskie");
    ui->comboStart->addItem("Mroźna");
    ui->comboStart->addItem("Muchobór Wielki");
    ui->comboStart->addItem("Muchobór Wielki (Roślinna)");
    ui->comboStart->addItem("Mydlice I");
    ui->comboStart->addItem("Mydlice II");
    ui->comboStart->addItem("Młodych Techników");
    ui->comboStart->addItem("NOWY DWÓR (pętla)");
    ui->comboStart->addItem("Na Grobli");
    ui->comboStart->addItem("Na Niskich Łąkach");
    ui->comboStart->addItem("Na Ostatnim Groszu");
    ui->comboStart->addItem("Na Szańcach");
    ui->comboStart->addItem("Narodowe Forum Muzyki");
    ui->comboStart->addItem("Niedziałkowskiego");
    ui->comboStart->addItem("Niedźwiedzia");
    ui->comboStart->addItem("Nowodworska");
    ui->comboStart->addItem("Nowowiejska");
    ui->comboStart->addItem("Nowy Dom");
    ui->comboStart->addItem("Nowy Dwór");
    ui->comboStart->addItem("Nowy Dwór (Rogowska)");
    ui->comboStart->addItem("Nowy Dwór (Stacja kolejowa)");
    ui->comboStart->addItem("Nyska");
    ui->comboStart->addItem("OPATOWICE");
    ui->comboStart->addItem("OPORÓW");
    ui->comboStart->addItem("OSIEDLE SOBIESKIEGO (pętla)");
    ui->comboStart->addItem("OSOBOWICE");
    ui->comboStart->addItem("OSOBOWICE (Stacja kolejowa)");
    ui->comboStart->addItem("OSOBOWICKA (Cmentarz II)");
    ui->comboStart->addItem("OSOBOWICKA (Cmentarz)");
    ui->comboStart->addItem("Obornicka (Obwodnica)");
    ui->comboStart->addItem("Oboźna");
    ui->comboStart->addItem("Odolanowska");
    ui->comboStart->addItem("Odrodzenia Polski");
    ui->comboStart->addItem("Ogród Botaniczny");
    ui->comboStart->addItem("Ojca Beyzyma");
    ui->comboStart->addItem("Okrzei");
    ui->comboStart->addItem("Oleśniczka");
    ui->comboStart->addItem("Oleśniczka - skrzyżowanie");
    ui->comboStart->addItem("Olsztyńska");
    ui->comboStart->addItem("Opatowicka nr 127");
    ui->comboStart->addItem("Opatowicka nr 59");
    ui->comboStart->addItem("Opatowicka nr 85");
    ui->comboStart->addItem("Opera");
    ui->comboStart->addItem("Opolska");
    ui->comboStart->addItem("Orla");
    ui->comboStart->addItem("Orlińskiego");
    ui->comboStart->addItem("Orzechowa");
    ui->comboStart->addItem("Os. Przyjaźni");
    ui->comboStart->addItem("Ostowa");
    ui->comboStart->addItem("Ostrowskiego");
    ui->comboStart->addItem("Owczarska");
    ui->comboStart->addItem("Ozorzyce-Krasińskiego");
    ui->comboStart->addItem("Oławska");
    ui->comboStart->addItem("Ołtaszyn");
    ui->comboStart->addItem("Ożynowa");
    ui->comboStart->addItem("PARK POŁUDNIOWY");
    ui->comboStart->addItem("PAWŁOWICE (Widawska)");
    ui->comboStart->addItem("PETRUSEWICZA");
    ui->comboStart->addItem("PIECOWICE");
    ui->comboStart->addItem("PILCZYCE");
    ui->comboStart->addItem("PILCZYCKA (Anima)");
    ui->comboStart->addItem("PL. DANIŁOWSKIEGO");
    ui->comboStart->addItem("PL. GRUNWALDZKI");
    ui->comboStart->addItem("PL. JANA PAWŁA II");
    ui->comboStart->addItem("PL. STASZICA");
    ui->comboStart->addItem("POCZTA POLSKA");
    ui->comboStart->addItem("POLANOWICE");
    ui->comboStart->addItem("POPOWICE (Stacja kolejowa)");
    ui->comboStart->addItem("PORT LOTNICZY");
    ui->comboStart->addItem("POŚWIĘCKA (Ośrodek zdrowia)");
    ui->comboStart->addItem("POŚWIĘTNE");
    ui->comboStart->addItem("PRACZE ODRZAŃSKIE");
    ui->comboStart->addItem("PRACZE ODRZAŃSKIE (Stacja kolejowa)");
    ui->comboStart->addItem("PSARY");
    ui->comboStart->addItem("PSIE POLE (Stacja kolejowa)");
    ui->comboStart->addItem("Palacha");
    ui->comboStart->addItem("Paprotna");
    ui->comboStart->addItem("Parafialna");
    ui->comboStart->addItem("Park Brochowski");
    ui->comboStart->addItem("Park Stabłowicki");
    ui->comboStart->addItem("Park Staromiejski");
    ui->comboStart->addItem("Park Szczytnicki");
    ui->comboStart->addItem("Park Tysiąclecia");
    ui->comboStart->addItem("Park Wschodni");
    ui->comboStart->addItem("Park Zachodni");
    ui->comboStart->addItem("Partynice");
    ui->comboStart->addItem("Partyzantów");
    ui->comboStart->addItem("Pasikurowice - n/ż");
    ui->comboStart->addItem("Pasikurowice-Energetyczna");
    ui->comboStart->addItem("Pasikurowice-Malinowa");
    ui->comboStart->addItem("Pasikurowice-cmentarz");
    ui->comboStart->addItem("Paulińska");
    ui->comboStart->addItem("Pawłowice");
    ui->comboStart->addItem("Pawłowicka");
    ui->comboStart->addItem("Pereca");
    ui->comboStart->addItem("Piastowska");
    ui->comboStart->addItem("Pietrzykowice");
    ui->comboStart->addItem("Piramowicza");
    ui->comboStart->addItem("Pisarzowice - Graniczna");
    ui->comboStart->addItem("Pisarzowice - Kolejowa");
    ui->comboStart->addItem("Pisarzowice - Odrzańska");
    ui->comboStart->addItem("Pisarzowice - Szkolna");
    ui->comboStart->addItem("Piwnika - Ponurego");
    ui->comboStart->addItem("Piłsudskiego");
    ui->comboStart->addItem("Pl. Hirszfelda");
    ui->comboStart->addItem("Pl. SOLIDARNOŚCI");
    ui->comboStart->addItem("Poczta Główna");
    ui->comboStart->addItem("Pola");
    ui->comboStart->addItem("Polanowicka");
    ui->comboStart->addItem("Poleska");
    ui->comboStart->addItem("Polkowicka");
    ui->comboStart->addItem("Pomorska");
    ui->comboStart->addItem("Popowice");
    ui->comboStart->addItem("Poprzeczna");
    ui->comboStart->addItem("Poznańska");
    ui->comboStart->addItem("Połabian");
    ui->comboStart->addItem("Poświęcka");
    ui->comboStart->addItem("Pracze Widawskie");
    ui->comboStart->addItem("Prudnicka");
    ui->comboStart->addItem("Prusa");
    ui->comboStart->addItem("Pruszowice - las");
    ui->comboStart->addItem("Pruszowice - wieś");
    ui->comboStart->addItem("Przebiśniegowa");
    ui->comboStart->addItem("Przedwiośnie (Stacja kolejowa)");
    ui->comboStart->addItem("Przybyszewskiego");
    ui->comboStart->addItem("Przybyły");
    ui->comboStart->addItem("Przyjaźni");
    ui->comboStart->addItem("Przystankowa");
    ui->comboStart->addItem("Psary - Parkowa");
    ui->comboStart->addItem("Psary - Szkoła");
    ui->comboStart->addItem("Psie Pole");
    ui->comboStart->addItem("Psie Pole (Gorlicka)");
    ui->comboStart->addItem("Psie Pole (Rondo Lotników Polskich)");
    ui->comboStart->addItem("Pustecka");
    ui->comboStart->addItem("Pułaskiego");
    ui->comboStart->addItem("Pułtuska");
    ui->comboStart->addItem("Północna");
    ui->comboStart->addItem("Płońskiego");
    ui->comboStart->addItem("RACŁAWICKA (pętla)");
    ui->comboStart->addItem("RATYŃ");
    ui->comboStart->addItem("ROD Bajki");
    ui->comboStart->addItem("ROD Bielany");
    ui->comboStart->addItem("ROD Mieczyk");
    ui->comboStart->addItem("ROD Oświata");
    ui->comboStart->addItem("ROD Pod Dębem");
    ui->comboStart->addItem("ROD Storczyk");
    ui->comboStart->addItem("ROD Tysiąclecia");
    ui->comboStart->addItem("ROD Zgoda");
    ui->comboStart->addItem("ROD Źródło Zdrowia");
    ui->comboStart->addItem("RUBCZAKA (Stacja kolejowa)");
    ui->comboStart->addItem("Racławicka");
    ui->comboStart->addItem("Racławicka (Gimnazjum nr 23)");
    ui->comboStart->addItem("Radio i Telewizja");
    ui->comboStart->addItem("Radomierzyce");
    ui->comboStart->addItem("Radwanice - Dębowa");
    ui->comboStart->addItem("Radwanice - Mickiewicza");
    ui->comboStart->addItem("Radwanice - Poprzeczna");
    ui->comboStart->addItem("Radwanice - Skrajna");
    ui->comboStart->addItem("Radwanice - Szkoła");
    ui->comboStart->addItem("Rakowiecka");
    ui->comboStart->addItem("Raków");
    ui->comboStart->addItem("Raków - skrzyżowanie");
    ui->comboStart->addItem("Raków - zakład");
    ui->comboStart->addItem("Ramiszów-kolonia");
    ui->comboStart->addItem("Ratyń - skrzyżowanie");
    ui->comboStart->addItem("Rdestowa");
    ui->comboStart->addItem("Redycka");
    ui->comboStart->addItem("Reja");
    ui->comboStart->addItem("Renoma");
    ui->comboStart->addItem("Robotnicza (Centrozłom)");
    ui->comboStart->addItem("Rogowska");
    ui->comboStart->addItem("Rondo");
    ui->comboStart->addItem("Rondo Obrońców Grodna");
    ui->comboStart->addItem("Roweckiego");
    ui->comboStart->addItem("Rubczaka");
    ui->comboStart->addItem("Rymarska");
    ui->comboStart->addItem("Rynek");
    ui->comboStart->addItem("Rysia");
    ui->comboStart->addItem("Rzemieślnicza");
    ui->comboStart->addItem("Różanka");
    ui->comboStart->addItem("RĘDZIN");
    ui->comboStart->addItem("RĘDZIŃSKA");
    ui->comboStart->addItem("Rękodzielnicza");
    ui->comboStart->addItem("SAMOTWÓR-PAŁAC");
    ui->comboStart->addItem("SIECHNICE - OSIEDLE");
    ui->comboStart->addItem("SIECHNICE - TIM");
    ui->comboStart->addItem("SOŁTYSOWICE");
    ui->comboStart->addItem("SPISKA (Ośrodek sportu)");
    ui->comboStart->addItem("STABŁOWICKA (Ośrodek zdrowia)");
    ui->comboStart->addItem("STADION WROCŁAW (Królewiecka)");
    ui->comboStart->addItem("STARODWORSKA (ZUW)");
    ui->comboStart->addItem("STĘPIN - pętla");
    ui->comboStart->addItem("SZCZODRE");
    ui->comboStart->addItem("SZYMANÓW");
    ui->comboStart->addItem("Samotworska");
    ui->comboStart->addItem("Samotwór - Dębowa");
    ui->comboStart->addItem("Sanocka");
    ui->comboStart->addItem("Semaforowa");
    ui->comboStart->addItem("Serbska (C.K. Agora)");
    ui->comboStart->addItem("Siechnice");
    ui->comboStart->addItem("Siechnice - CPN n ż");
    ui->comboStart->addItem("Siechnice - Elektrociepłownia");
    ui->comboStart->addItem("Siechnice - Ogrodnictwo");
    ui->comboStart->addItem("Siechnice - Staszica");
    ui->comboStart->addItem("Siechnice - Szkolna");
    ui->comboStart->addItem("Siechnice - Wiadukt");
    ui->comboStart->addItem("Siechnice - ZOZ");
    ui->comboStart->addItem("Siechnice - Zacisze");
    ui->comboStart->addItem("Siedlec-skrzyżowanie");
    ui->comboStart->addItem("Siedlec-szkoła");
    ui->comboStart->addItem("Skarbowców");
    ui->comboStart->addItem("Skarżyńskiego");
    ui->comboStart->addItem("Skała");
    ui->comboStart->addItem("Skierniewicka");
    ui->comboStart->addItem("Skwerowa");
    ui->comboStart->addItem("Smardzów - Reja");
    ui->comboStart->addItem("Smocza");
    ui->comboStart->addItem("Solskiego");
    ui->comboStart->addItem("Sosnowiecka");
    ui->comboStart->addItem("Sowia");
    ui->comboStart->addItem("Sołtysowicka");
    ui->comboStart->addItem("Spółdzielcza");
    ui->comboStart->addItem("Stabłowice");
    ui->comboStart->addItem("Stabłowicka (Szkoła Podstawowa nr 22)");
    ui->comboStart->addItem("Stadion Olimpijski");
    ui->comboStart->addItem("Stadion Wrocław (Lotnicza)");
    ui->comboStart->addItem("Stalowa");
    ui->comboStart->addItem("Stanisławowska");
    ui->comboStart->addItem("Stanki");
    ui->comboStart->addItem("Starodworska");
    ui->comboStart->addItem("Starodębowa");
    ui->comboStart->addItem("Strachowice General Aviation");
    ui->comboStart->addItem("Strachowicka");
    ui->comboStart->addItem("Strachowskiego");
    ui->comboStart->addItem("Strumykowa");
    ui->comboStart->addItem("Strzegomska 56");
    ui->comboStart->addItem("Stępin");
    ui->comboStart->addItem("Sucha");
    ui->comboStart->addItem("Sudecka");
    ui->comboStart->addItem("Sulimów");
    ui->comboStart->addItem("Suwalska");
    ui->comboStart->addItem("Swojczyce");
    ui->comboStart->addItem("Swojczycka");
    ui->comboStart->addItem("Szczecińska");
    ui->comboStart->addItem("Szczepin");
    ui->comboStart->addItem("Szczodre - Szkoła");
    ui->comboStart->addItem("Szczodre - Trzebnicka");
    ui->comboStart->addItem("Szczodre - stawy");
    ui->comboStart->addItem("Szewczenki");
    ui->comboStart->addItem("Szkocka");
    ui->comboStart->addItem("Szkolna");
    ui->comboStart->addItem("Szkoła Żerniki");
    ui->comboStart->addItem("Sztabowa");
    ui->comboStart->addItem("Szybowcowa");
    ui->comboStart->addItem("Szymanów - skrzyż.");
    ui->comboStart->addItem("Sąsiedzka");
    ui->comboStart->addItem("SĘPOLNO");
    ui->comboStart->addItem("Słoneczna");
    ui->comboStart->addItem("Słowiańska");
    ui->comboStart->addItem("TARNOGAJ");
    ui->comboStart->addItem("TRESTNO (pętla)");
    ui->comboStart->addItem("TRZMIELOWICKA (Stacja kolejowa)");
    ui->comboStart->addItem("TYNIECKA (pętla)");
    ui->comboStart->addItem("Tczewska");
    ui->comboStart->addItem("Tokary");
    ui->comboStart->addItem("Tokary - osiedle");
    ui->comboStart->addItem("Topolowa");
    ui->comboStart->addItem("Tramwajowa");
    ui->comboStart->addItem("Transbud");
    ui->comboStart->addItem("Trawowa");
    ui->comboStart->addItem("Trestno");
    ui->comboStart->addItem("Trzebnicka");
    ui->comboStart->addItem("Trzmielowicka");
    ui->comboStart->addItem("Tunelowa");
    ui->comboStart->addItem("Turoszowska");
    ui->comboStart->addItem("Twardogórska");
    ui->comboStart->addItem("Tymiankowa");
    ui->comboStart->addItem("Tyniecka");
    ui->comboStart->addItem("Tyrmanda");
    ui->comboStart->addItem("Uniwersytecka");
    ui->comboStart->addItem("Uniwersytet");
    ui->comboStart->addItem("Uniwersytet Ekonomiczny");
    ui->comboStart->addItem("Uniwersytet Medyczny");
    ui->comboStart->addItem("Urząd Wojewódzki");
    ui->comboStart->addItem("Volvo");
    ui->comboStart->addItem("Volvo - brama II");
    ui->comboStart->addItem("WAŁBRZYSKA");
    ui->comboStart->addItem("WOJANOWSKA (pętla)");
    ui->comboStart->addItem("WOJNÓW (pętla)");
    ui->comboStart->addItem("Wallenroda");
    ui->comboStart->addItem("Warmińska");
    ui->comboStart->addItem("Wawrzyniaka");
    ui->comboStart->addItem("Weigla (Szpital)");
    ui->comboStart->addItem("Wejherowska");
    ui->comboStart->addItem("Wełniana");
    ui->comboStart->addItem("Wiaduktowa");
    ui->comboStart->addItem("Widawa");
    ui->comboStart->addItem("Wiejska");
    ui->comboStart->addItem("Wielka");
    ui->comboStart->addItem("Wielkopolska");
    ui->comboStart->addItem("Wilczyce");
    ui->comboStart->addItem("Wilczyce - Dębowa");
    ui->comboStart->addItem("Wilczyce - Sosnowa");
    ui->comboStart->addItem("Wilczyce - Szkoła");
    ui->comboStart->addItem("Wilczyce - Wilczycka");
    ui->comboStart->addItem("Wilczyce - stary młyn");
    ui->comboStart->addItem("Wilkszyn (pętla)");
    ui->comboStart->addItem("Wilkszyn - Miłoszyn");
    ui->comboStart->addItem("Wilkszyn - Polna");
    ui->comboStart->addItem("Wilkszyńska");
    ui->comboStart->addItem("Wita Stwosza");
    ui->comboStart->addItem("Witkowska");
    ui->comboStart->addItem("Wiślańska");
    ui->comboStart->addItem("Wiśniowa");
    ui->comboStart->addItem("Wojanowska");
    ui->comboStart->addItem("Wojnów");
    ui->comboStart->addItem("Wojszyce");
    ui->comboStart->addItem("Wojszycka");
    ui->comboStart->addItem("Wolska");
    ui->comboStart->addItem("Wołowska");
    ui->comboStart->addItem("Wrocławski Park Przemysłowy");
    ui->comboStart->addItem("Wrocławski Park Technologiczny");
    ui->comboStart->addItem("Wschowska");
    ui->comboStart->addItem("Wysoka");
    ui->comboStart->addItem("Wysoka Osiedle");
    ui->comboStart->addItem("Wysoka-Chabrowa");
    ui->comboStart->addItem("Wysoka-Radosna");
    ui->comboStart->addItem("Wyszyńskiego");
    ui->comboStart->addItem("Wyścigowa");
    ui->comboStart->addItem("Wyższa Szkoła Bankowa");
    ui->comboStart->addItem("Wzgórze Partyzantów");
    ui->comboStart->addItem("Węgrów");
    ui->comboStart->addItem("ZABRODZIE");
    ui->comboStart->addItem("ZACHODNIA (Stacja kolejowa)");
    ui->comboStart->addItem("ZAKRZÓW");
    ui->comboStart->addItem("ZAWALNA");
    ui->comboStart->addItem("ZOO");
    ui->comboStart->addItem("Zacisze");
    ui->comboStart->addItem("Zagony");
    ui->comboStart->addItem("Zagrodnicza");
    ui->comboStart->addItem("Zagłoby");
    ui->comboStart->addItem("Zagłębiowska");
    ui->comboStart->addItem("Zajazdowa");
    ui->comboStart->addItem("Zajezdnia BOREK");
    ui->comboStart->addItem("Zajezdnia GAJ");
    ui->comboStart->addItem("Zajezdnia Obornicka");
    ui->comboStart->addItem("Zajezdnia OŁBIN");
    ui->comboStart->addItem("Zajączkowska");
    ui->comboStart->addItem("Zakrzowska");
    ui->comboStart->addItem("Zalewowa");
    ui->comboStart->addItem("Zaporoska");
    ui->comboStart->addItem("Zaprężyn");
    ui->comboStart->addItem("Zaprężyn - skrzyżowanie");
    ui->comboStart->addItem("Zarembowicza");
    ui->comboStart->addItem("Zbożowa");
    ui->comboStart->addItem("Zemska");
    ui->comboStart->addItem("Zgorzelisko");
    ui->comboStart->addItem("Zielińskiego");
    ui->comboStart->addItem("Zielna");
    ui->comboStart->addItem("Ziemniaczana");
    ui->comboStart->addItem("Zimowa");
    ui->comboStart->addItem("Zwycięska");
    ui->comboStart->addItem("ZĘBICE - pętla");
    ui->comboStart->addItem("Zębice - Prusa");
    ui->comboStart->addItem("Zębice - Trzech Lip/Prusa");
    ui->comboStart->addItem("Złotnicka");
    ui->comboStart->addItem("Złotniki");
    ui->comboStart->addItem("Złotostocka");
    ui->comboStart->addItem("most Grunwaldzki");
    ui->comboStart->addItem("most Milenijny");
    ui->comboStart->addItem("most Osobowicki");
    ui->comboStart->addItem("mosty Mieszczańskie");
    ui->comboStart->addItem("pl. Bema");
    ui->comboStart->addItem("pl. Legionów");
    ui->comboStart->addItem("pl. Nowy Targ");
    ui->comboStart->addItem("pl. Orląt Lwowskich");
    ui->comboStart->addItem("pl. Srebrny");
    ui->comboStart->addItem("pl. Strzegomski (Muzeum Współczesne)");
    ui->comboStart->addItem("pl. Wróblewskiego");
    ui->comboStart->addItem("pl. Zgody");
    ui->comboStart->addItem("ŁOZINA");
    ui->comboStart->addItem("Łosice");
    ui->comboStart->addItem("Łososiowicka");
    ui->comboStart->addItem("Łozina - Milicka");
    ui->comboStart->addItem("Łozina - Nowego Osiedla I");
    ui->comboStart->addItem("Łozina - Nowego Osiedla II");
    ui->comboStart->addItem("Łozina - Ośrodek zdrowia");
    ui->comboStart->addItem("Łozina - Wrocławska");
    ui->comboStart->addItem("Łozina - cmentarz");
    ui->comboStart->addItem("Ługowa");
    ui->comboStart->addItem("Łukaszowice");
    ui->comboStart->addItem("Łużycka");
    ui->comboStart->addItem("ŚLAZOWA (pętla)");
    ui->comboStart->addItem("ŚWIDNICKA (Dom Europy)");
    ui->comboStart->addItem("ŚWINIARY (pętla)");
    ui->comboStart->addItem("Śliczna");
    ui->comboStart->addItem("Śliwice");
    ui->comboStart->addItem("Śliwowa");
    ui->comboStart->addItem("Ślusarska");
    ui->comboStart->addItem("Ślęza (ul. Dębowa)");
    ui->comboStart->addItem("Ślęza (ul. Przystankowa)");
    ui->comboStart->addItem("Ślęza (ul. Pszenna - autostrada)");
    ui->comboStart->addItem("Śniadeckich");
    ui->comboStart->addItem("Śnieżna");
    ui->comboStart->addItem("Średzka");
    ui->comboStart->addItem("Śrubowa");
    ui->comboStart->addItem("Św. Katarzyna - Główna");
    ui->comboStart->addItem("Św. Katarzyna - Główna n ż");
    ui->comboStart->addItem("Św. Katarzyna - Parkowa");
    ui->comboStart->addItem("Św. Katarzyna - stacja");
    ui->comboStart->addItem("Św. Katarzyna - szkoła");
    ui->comboStart->addItem("Św. Katarzyna - szpital");
    ui->comboStart->addItem("Św. Katarzyna - Żernicka");
    ui->comboStart->addItem("Świdnicka");
    ui->comboStart->addItem("Świeradowska");
    ui->comboStart->addItem("Świstackiego");
    ui->comboStart->addItem("Świętokrzyska");
    ui->comboStart->addItem("ŻAR");
    ui->comboStart->addItem("ŻERNIKI WROCŁAWSKIE");
    ui->comboStart->addItem("Żelazna");
    ui->comboStart->addItem("Żernicka");
    ui->comboStart->addItem("Żernicka (Stacja kolejowa)");
    ui->comboStart->addItem("Żerniki");
    ui->comboStart->addItem("Żerniki Wr. - Kolejowa");
    ui->comboStart->addItem("Żerniki Wr. - Orla");
    ui->comboStart->addItem("Żmigrodzka (Obwodnica)");
    ui->comboStart->addItem("Żmudzka");
}
